media-libs/gegl: add missing -lm to tests, bug #639986
The change fixes underlinking on ia64:
```
gnu/bin/ld: buffer-test.o: undefined reference to symbol 'floor@@GLIBC_2.2'
/usr/lib/gcc/ia64-unknown-linux-gnu/9.2.0/../../../../ia64-unknown-linux-gnu/bin/ld:
    /lib/libm.so.6.1: error adding symbols: DSO missing from command line
```

Closes: https://bugs.gentoo.org/639986
Package-Manager: Portage-2.3.84, Repoman-2.3.20
Signed-off-by: Sergei Trofimovich <slyfox@gentoo.org>